[package]
name = "p2pc-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
libp2p = "0.53.2"
log = "0.4.21"
p2pc = { version = "0.1.0", path = "../p2pc" }
tokio = { version = "1.37.0", features = ["full"] }
